### ISSUE TITLE
Cannons not working...

### ISSUE THREAD

**Issue by Devboi** [sunkid/Armageddon#1]
The guns and grenades work but when I try to hit a cannon with a torch I get this in the console.

2011-10-09 09:30:00 [SEVERE] Could not pass event PLAYER_INTERACT to Armageddon
java.lang.NullPointerException
    at com.iminurnetz.bukkit.plugin.armageddon.ArmageddonPlugin.getCannon(ArmageddonPlugin.java:357)
    at com.iminurnetz.bukkit.plugin.armageddon.listeners.ArmageddonPlayerListener.onPlayerInteract(ArmageddonPlayerListener.java:126)
    at org.bukkit.plugin.java.JavaPluginLoader$11.execute(JavaPluginLoader.java:314)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
    at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:171)
    at net.minecraft.server.ItemInWorldManager.dig(ItemInWorldManager.java:92)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:497)
    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:160)
    at net.minecraft.server.Packet14BlockDig.a(SourceFile:43)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:500)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:471)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

And this when I am trying to fire one 

2011-10-09 09:30:46 [SEVERE] Could not pass event BLOCK_DISPENSE to Armageddon
java.lang.NullPointerException
    at com.iminurnetz.bukkit.plugin.armageddon.ArmageddonPlugin.getCannon(ArmageddonPlugin.java:357)
    at com.iminurnetz.bukkit.plugin.armageddon.listeners.ArmageddonBlockListener.onBlockDispense(ArmageddonBlockListener.java:77)
    at org.bukkit.plugin.java.JavaPluginLoader$44.execute(JavaPluginLoader.java:547)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
    at net.minecraft.server.BlockDispenser.dispense(BlockDispenser.java:129)
    at net.minecraft.server.BlockDispenser.a(BlockDispenser.java:193)
    at org.getspout.spout.block.mcblock.CustomContainer.a(CustomContainer.java:183)
    at net.minecraft.server.World.a(World.java:2143)
    at net.minecraft.server.World.doTick(World.java:1637)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:461)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

Any ideas why??
thanks

**Comment by sunkid** [comment]
It looks like your cannons file got corrupted. Try moving aside plugins/Armageddon/cannons.ser after stopping your server.

**Comment by mot4b** [comment]
I have the same error. What do you mean by moving aside the file?

**Comment by sunkid** [comment]
There should be a file names cannons.ser in the plugins/Armageddon folder. Just delete it.

**Comment by Devboi** [comment]
its ok I have fixed the cannons...
There is a problem with a conflict with the WAR plugin...
WAR does not recognise the explosions and spams the console so I can now only use the cannons and tnt grenade without lagging the server.

I know this is not ur issue just thought I would let u know in case ppl ask in future. War conflicts with Armageddon
