### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by choyiny** [sunkid/Armageddon#2]
2011-10-14 04:16:41 [INFO] [Armageddon 2.4.2] Server version compatibility check succeeded
2011-10-14 04:16:41 [SEVERE] Error occurred while enabling Armageddon v2.4.2 (Is it up to date?): com.iminurnetz.bukkit.plugin.BukkitPlugin.getConfig()Lorg/bukkit/configuration/file/FileConfiguration;
java.lang.NoSuchMethodError: com.iminurnetz.bukkit.plugin.BukkitPlugin.getConfig()Lorg/bukkit/configuration/file/FileConfiguration;
at com.iminurnetz.bukkit.plugin.util.ConfigurationService.load(ConfigurationService.java:76)
at com.iminurnetz.bukkit.plugin.util.ConfigurationService.<init>(ConfigurationService.java:53)
at com.iminurnetz.bukkit.plugin.armageddon.ArmageddonConfiguration.<init>(ArmageddonConfiguration.java:82)
at com.iminurnetz.bukkit.plugin.armageddon.ArmageddonPlugin.enablePlugin(ArmageddonPlugin.java:120)

**Comment by choyiny** [comment]
org.bukkit.command.CommandException: Unhandled exception executing command 'cb' in plugin Armageddon v2.4.2
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:358)
at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:757)
at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:722)
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:715)
at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:471)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
Caused by: java.lang.NullPointerException
at com.iminurnetz.bukkit.plugin.armageddon.ArmageddonPlugin.onCommand(ArmageddonPlugin.java:208)
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
... 12 more

**Comment by sunkid** [comment]
Can you please make sure you have the latest BaseBukkitPlugin.jar installed and that you also have the latest of any of my other plugins (if any)? See http://dev.bukkit.org/profiles/sunkid for a list of them.

**Comment by choyiny** [comment]
I have basebukkit and armageddon together. Not anymore, it is up to date

**Comment by sunkid** [comment]
It turns out that I had uploaded the wrong version of the jar to dev.bukkit.org. My apologies. Please try the latest from https://github.com/sunkid/BaseBukkitPlugin/tree/master/release while the correct version is being approved for DBO.

**Comment by eatrowbridge** [comment]
I downloaded the latest from your link above, and i'm still getting the (is it up to date?) error.

Any thoughts?

**Comment by darkcloud784** [comment]
I'm pretty sure it could be your not running bukkit 1317. I had this problem until I moved from 1240 to 1317. However there is still an error on enable that you get with 1317. Completely default config, with no other plugins installed. I also made sure I downloaded the proper release from github rather than DBO. Not 100% sure why this requires so many changes per version or for that matter a base dependency.

2011-10-18 01:30:54 [SEVERE] [Armageddon 2.4.2] Error enabling! ABORTED
java.lang.NullPointerException
    at com.iminurnetz.bukkit.util.MaterialUtils.getList(MaterialUtils.java:655)
    at com.iminurnetz.bukkit.util.MaterialUtils.getMaterial(MaterialUtils.java:676)
    at com.iminurnetz.bukkit.plugin.armageddon.ArmageddonConfiguration.<init>(ArmageddonConfiguration.java:157)
    at com.iminurnetz.bukkit.plugin.armageddon.ArmageddonPlugin.enablePlugin(ArmageddonPlugin.java:120)
    at com.iminurnetz.bukkit.plugin.BukkitPlugin.onEnable(BukkitPlugin.java:148)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:170)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:957)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:280)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:171)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:154)
    at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:297)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:284)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:348)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
2011-10-18 01:30:54 [INFO] [Armageddon 2.4.2] disabled.

**Comment by eatrowbridge** [comment]
i have bukkit 1317.

**Comment by eatrowbridge** [comment]
I made sure i had the latest craftbukkit. now this is what i get.

11:06:18 [INFO] This server is running Craftbukkit version git-Bukkit-0.0.0-1126
-g35eac7a-b1317jnks (MC: 1.8.1)
11:06:18 [INFO] [Armageddon 2.4.2] initialized
11:06:19 [INFO] [BaseBukkitPlugin 1.7] initialized
11:06:19 [INFO] Preparing level "Ted"
11:06:19 [INFO] Default game type: 0
11:06:19 [INFO] Preparing start region for level 0 (Seed: -8040155283517205)
11:06:19 [INFO] Preparing start region for level 1 (Seed: 2846670914762914777)
11:06:20 [INFO] Preparing spawn area: 28%
11:06:20 [INFO] [Armageddon 2.4.2] Server version compatibility check succeeded
11:06:20 [SEVERE] [Armageddon 2.4.2] Unknown grenade type 'SOUL_SAND'; IGNORED!
11:06:20 [SEVERE] [Armageddon 2.4.2] Unknown grenade type 'CLAY_BALL'; IGNORED!
11:06:20 [SEVERE] [Armageddon 2.4.2] Unknown grenade type 'SLIME_BALL'; IGNORED!

11:06:20 [SEVERE] [Armageddon 2.4.2] Unknown grenade type 'TNT'; IGNORED!
11:06:20 [SEVERE] [Armageddon 2.4.2] Unknown grenade type 'GOLDEN_APPLE'; IGNORE
D!
11:06:20 [SEVERE] [Armageddon 2.4.2] Unknown grenade type 'LAVA_BUCKET'; IGNORED
!
11:06:20 [SEVERE] [Armageddon 2.4.2] Unknown grenade type 'WATER_BUCKET'; IGNORE
D!
11:06:20 [SEVERE] [Armageddon 2.4.2] Unknown grenade type 'STRING'; IGNORED!
11:06:20 [SEVERE] [Armageddon 2.4.2] Error enabling! ABORTED
java.lang.NullPointerException
        at com.iminurnetz.bukkit.util.MaterialUtils.getList(MaterialUtils.java:6
55)
        at com.iminurnetz.bukkit.util.MaterialUtils.getMaterial(MaterialUtils.ja
va:676)
        at com.iminurnetz.bukkit.plugin.armageddon.ArmageddonConfiguration.<init

> (ArmageddonConfiguration.java:157)
>         at com.iminurnetz.bukkit.plugin.armageddon.ArmageddonPlugin.enablePlugin
> (ArmageddonPlugin.java:120)
>         at com.iminurnetz.bukkit.plugin.BukkitPlugin.onEnable(BukkitPlugin.java:
> 148)
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:170)
>         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
> .java:957)
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
> r.java:280)
>         at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:171)
>         at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:154
> )
>         at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:297)
>         at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:284)
>         at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:152)
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:348)
>         at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
> 11:06:20 [INFO] [Armageddon 2.4.2] disabled.
> 11:06:20 [INFO] [BaseBukkitPlugin 1.7] Server version compatibility check succee
> ded
> 11:06:20 [INFO] Server permissions file permissions.yml is empty, ignoring it
> 11:06:20 [INFO] Done (0.187s)! For help, type "help" or "?"

**Comment by sunkid** [comment]
I just uploaded a new version. Please give it a try. Make sure to remove BaseBukkitPlugin.jar from your plugins folder. If this error persists, please pastie your configuration file.

**Comment by wingsman2** [comment]
I am also having the same issue above with not being able to load Armageddon 2.5

2011-10-19 10:39:19 [INFO] [Armageddon 2.5] Server version compatibility check succeeded
2011-10-19 10:39:19 [SEVERE] [Armageddon 2.5] Unknown grenade type 'SOUL_SAND'; IGNORED!
2011-10-19 10:39:19 [SEVERE] [Armageddon 2.5] Unknown grenade type 'CLAY_BALL'; IGNORED!
2011-10-19 10:39:19 [SEVERE] [Armageddon 2.5] Unknown grenade type 'SLIME_BALL'; IGNORED!
2011-10-19 10:39:19 [SEVERE] [Armageddon 2.5] Unknown grenade type 'TNT'; IGNORED!
2011-10-19 10:39:19 [SEVERE] [Armageddon 2.5] Unknown grenade type 'GOLDEN_APPLE'; IGNORED!
2011-10-19 10:39:19 [SEVERE] [Armageddon 2.5] Unknown grenade type 'LAVA_BUCKET'; IGNORED!
2011-10-19 10:39:19 [SEVERE] [Armageddon 2.5] Unknown grenade type 'WATER_BUCKET'; IGNORED!
2011-10-19 10:39:19 [SEVERE] [Armageddon 2.5] Unknown grenade type 'STRING'; IGNORED!
2011-10-19 10:39:19 [SEVERE] [Armageddon 2.5] Error enabling! ABORTED
java.lang.NullPointerException
    at com.iminurnetz.bukkit.util.MaterialUtils.getList(MaterialUtils.java:655)
    at com.iminurnetz.bukkit.util.MaterialUtils.getMaterial(MaterialUtils.java:676)
    at com.iminurnetz.bukkit.plugin.armageddon.ArmageddonConfiguration.<init>(ArmageddonConfiguration.java:157)
    at com.iminurnetz.bukkit.plugin.armageddon.ArmageddonPlugin.enablePlugin(ArmageddonPlugin.java:120)
    at com.iminurnetz.bukkit.plugin.BukkitPlugin.onEnable(BukkitPlugin.java:162)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:170)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:957)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:280)
    at com.bukkit.sharkiller.milkAdmin.WebServer.run(Unknown Source)
2011-10-19 10:39:19 [INFO] [Armageddon 2.5] disabled.

**Comment by darkcloud784** [comment]
http://pastebin.com/kbpcajzy

The basebukkitplugin unpacks to the armageddon folder (not sure if thats supposed to happen)

Error:

2011-10-19 13:29:16 [INFO] [Armageddon 2.5] Server version compatibility check succeeded
2011-10-19 13:29:16 [INFO] [Armageddon 2.5] BaseBukkitPlugin version check...
2011-10-19 13:29:16 [INFO] [BaseBukkitPlugin 1.8] initialized
2011-10-19 13:29:16 [INFO] [BaseBukkitPlugin 1.8] Server version compatibility check succeeded
2011-10-19 13:29:16 [SEVERE] Error occurred while enabling Armageddon v2.5 (Is it up to date?): com.iminurnetz.bukkit.plugin.BukkitPlugin.getConfig()Lorg/bukkit/configuration/file/FileConfiguration;
java.lang.NoSuchMethodError: com.iminurnetz.bukkit.plugin.BukkitPlugin.getConfig()Lorg/bukkit/configuration/file/FileConfiguration;
    at com.iminurnetz.bukkit.plugin.util.ConfigurationService.load(ConfigurationService.java:76)
    at com.iminurnetz.bukkit.plugin.util.ConfigurationService.<init>(ConfigurationService.java:53)
    at com.iminurnetz.bukkit.plugin.armageddon.ArmageddonConfiguration.<init>(ArmageddonConfiguration.java:82)
    at com.iminurnetz.bukkit.plugin.armageddon.ArmageddonPlugin.enablePlugin(ArmageddonPlugin.java:120)
    at com.iminurnetz.bukkit.plugin.BukkitPlugin.onEnable(BukkitPlugin.java:162)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:126)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:941)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:280)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:174)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:157)
    at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:297)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:284)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:348)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

**Comment by sunkid** [comment]
This indicates that you are on an older CraftBukkit release. Please make sure to install the latest recommended build (1337 as of yesterday, but 1317 will work as well).

**Comment by darkcloud784** [comment]
Thx didnt know there was another update XD. Did the bukkit update and it works perfectly now =D

**Comment by sunkid** [comment]
glad it works! :)
