### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by darkcloud784** [sunkid/Armageddon#3]
When we reload the server with COMPLETE default config. version in config says 1.4 bukkit dev version 2.4.2. Bukkit build 1240

[CODE]2011-10-14 11:09:49 [SEVERE] Error occurred while enabling Armageddon v2.4.2 (Is it up to date?): com.iminurnetz.bukkit.plugin.BukkitPlugin.getConfig()Lorg/bukkit/configuration/file/FileConfiguration;
java.lang.NoSuchMethodError: com.iminurnetz.bukkit.plugin.BukkitPlugin.getConfig()Lorg/bukkit/configuration/file/FileConfiguration;
    at com.iminurnetz.bukkit.plugin.util.ConfigurationService.load(ConfigurationService.java:76)
    at com.iminurnetz.bukkit.plugin.util.ConfigurationService.<init>(ConfigurationService.java:53)
    at com.iminurnetz.bukkit.plugin.armageddon.ArmageddonConfiguration.<init>(ArmageddonConfiguration.java:82)
    at com.iminurnetz.bukkit.plugin.armageddon.ArmageddonPlugin.enablePlugin(ArmageddonPlugin.java:120)
    at com.iminurnetz.bukkit.plugin.BukkitPlugin.onEnable(BukkitPlugin.java:148)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:126)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:941)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:280)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:174)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:157)
    at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:416)
    at org.bukkit.Bukkit.reload(Bukkit.java:182)
    at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:22)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:358)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:354)
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:506)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:485)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)[/CODE]

When we use /cb commands bukkit crys:

[CODE]2011-10-14 11:09:49 [SEVERE] Error occurred while enabling Armageddon v2.4.2 (Is it up to date?): com.iminurnetz.bukkit.plugin.BukkitPlugin.getConfig()Lorg/bukkit/configuration/file/FileConfiguration;
java.lang.NoSuchMethodError: com.iminurnetz.bukkit.plugin.BukkitPlugin.getConfig()Lorg/bukkit/configuration/file/FileConfiguration;
    at com.iminurnetz.bukkit.plugin.util.ConfigurationService.load(ConfigurationService.java:76)
    at com.iminurnetz.bukkit.plugin.util.ConfigurationService.<init>(ConfigurationService.java:53)
    at com.iminurnetz.bukkit.plugin.armageddon.ArmageddonConfiguration.<init>(ArmageddonConfiguration.java:82)
    at com.iminurnetz.bukkit.plugin.armageddon.ArmageddonPlugin.enablePlugin(ArmageddonPlugin.java:120)
    at com.iminurnetz.bukkit.plugin.BukkitPlugin.onEnable(BukkitPlugin.java:148)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:126)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:941)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:280)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:174)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:157)
    at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:416)
    at org.bukkit.Bukkit.reload(Bukkit.java:182)
    at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:22)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:358)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:354)
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:506)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:485)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)[/CODE]

**Comment by sunkid** [comment]
Can you please check that you have the latest BaseBukkitPlugin.jar and that you also have the latest of the WorldModes, CreativeStick, or LongGrass plugins in case you are using any of them. You can get all latest versions at http://dev.bukkit.org/profiles/sunkid/ !

**Comment by darkcloud784** [comment]
I have the newest basebukkitplugin, not using worldmodes, creativestick, or longGrass.

Edit: re-updated basebukkitplugin to ensure it was updated properly. Will report back any results if they have changed.

Update: Still getting this error after ensuring im on the newest basebukkitplugin.

2011-10-16 15:03:34 [INFO] [Armageddon 2.4.2] Server version compatibility check succeeded
2011-10-16 15:03:34 [SEVERE] Error occurred while enabling Armageddon v2.4.2 (Is it up to date?): com.iminurnetz.bukkit.plugin.BukkitPlugin.getConfig()Lorg/bukkit/configuration/file/FileConfiguration;
java.lang.NoSuchMethodError: com.iminurnetz.bukkit.plugin.BukkitPlugin.getConfig()Lorg/bukkit/configuration/file/FileConfiguration;
    at com.iminurnetz.bukkit.plugin.util.ConfigurationService.load(ConfigurationService.java:76)
    at com.iminurnetz.bukkit.plugin.util.ConfigurationService.<init>(ConfigurationService.java:53)
    at com.iminurnetz.bukkit.plugin.armageddon.ArmageddonConfiguration.<init>(ArmageddonConfiguration.java:82)
    at com.iminurnetz.bukkit.plugin.armageddon.ArmageddonPlugin.enablePlugin(ArmageddonPlugin.java:120)
    at com.iminurnetz.bukkit.plugin.BukkitPlugin.onEnable(BukkitPlugin.java:148)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:126)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:941)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:280)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:174)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:157)
    at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:416)
    at org.bukkit.Bukkit.reload(Bukkit.java:182)
    at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:22)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:358)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:354)
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:506)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:485)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

**Comment by darkcloud784** [comment]
Also wanted to let you know that the newest version of your basebukkitplugin.jar is labeled as 1.8 on bukkit dev but the plugin.yml shows 1.7

**Comment by sunkid** [comment]
Thank you very much for pointing this out! It turns out that I had uploaded the wrong version of the jar to dev.bukkit.org. My apologies. Please try the latest from https://github.com/sunkid/BaseBukkitPlugin/tree/master/release while the correct version is being approved for DBO.

**Comment by darkcloud784** [comment]
I'm still getting this error after downloading the newest version from github.

2011-10-18 01:30:54 [SEVERE] [Armageddon 2.4.2] Error enabling! ABORTED
java.lang.NullPointerException
    at com.iminurnetz.bukkit.util.MaterialUtils.getList(MaterialUtils.java:655)
    at com.iminurnetz.bukkit.util.MaterialUtils.getMaterial(MaterialUtils.java:676)
    at com.iminurnetz.bukkit.plugin.armageddon.ArmageddonConfiguration.<init>(ArmageddonConfiguration.java:157)
    at com.iminurnetz.bukkit.plugin.armageddon.ArmageddonPlugin.enablePlugin(ArmageddonPlugin.java:120)
    at com.iminurnetz.bukkit.plugin.BukkitPlugin.onEnable(BukkitPlugin.java:148)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:170)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:957)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:280)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:171)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:154)
    at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:297)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:284)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:348)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
2011-10-18 01:30:54 [INFO] [Armageddon 2.4.2] disabled.
