### ISSUE TITLE
Error on hitting dispenser with a torch (v2.92)

### ISSUE THREAD

**Issue by Skyve** [sunkid/Armageddon#8]
11:32:11 [SEVERE] Could not pass event org.bukkit.event.player.PlayerInteractEvent to Armageddon
java.lang.NullPointerException
        at com.iminurnetz.bukkit.plugin.armageddon.ArmageddonPlugin.getCannon(ArmageddonPlugin.java:357)
        at com.iminurnetz.bukkit.plugin.armageddon.listeners.ArmageddonPlayerListener.onPlayerInteract(ArmageddonPlayerListener.java:126)
        at org.bukkit.plugin.java.JavaPluginLoader$11.execute(JavaPluginLoader.java:340)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:57)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:453)
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:187)
        at net.minecraft.server.ItemInWorldManager.dig(ItemInWorldManager.java:92)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:507)
        at net.minecraft.server.Packet14BlockDig.handle(SourceFile:43)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:100)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:537)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)

**Comment by Skyve** [comment]
Hm, it seems this has been resolved by erasing config.
